# Dired colon verbs — registered via colon/define (plugin hook)

(colon/define "Drename"     (fn [rest] (editor/run-command "dired-rename"              (string/trim rest))))
(colon/define "Dcopy"       (fn [rest] (editor/run-command "dired-copy"                (string/trim rest))))
(colon/define "Dmove"       (fn [rest] (editor/run-command "dired-move"                (string/trim rest))))
(colon/define "Dsymlink"    (fn [rest] (editor/run-command "dired-symlink"             (string/trim rest))))
(colon/define "Dmkdir"      (fn [rest] (editor/run-command "dired-mkdir"               (string/trim rest))))
(colon/define "Dfilter"     (fn [rest] (editor/run-command "dired-filter"              (string/trim rest))))
(colon/define "Dclear"      (fn [rest] (editor/run-command "dired-clear-filter"        (string/trim rest))))
(colon/define "Dmark"       (fn [rest] (editor/run-command "dired-mark"                (string/trim rest))))
(colon/define "Dcopymark"   (fn [&]    (editor/run-command "dired-mark-with-type"      "copy")))
(colon/define "Dmovemark"   (fn [&]    (editor/run-command "dired-mark-with-type"      "move")))
(colon/define "Dsort"       (fn [&]    (editor/run-command "dired-toggle-sort")))
(colon/define "Dsortr"      (fn [&]    (editor/run-command "dired-toggle-sort-reverse")))
(colon/define "Dhidden"     (fn [&]    (editor/run-command "dired-toggle-hidden")))
(colon/define "Dinv"        (fn [&]    (editor/run-command "dired-invert-marks")))
(colon/define "Dunmark"     (fn [&]    (editor/run-command "dired-unmark-all")))
(colon/define "Dexec-copy"  (fn [rest] (editor/run-command "dired-execute-copy"        (string/trim rest))))
(colon/define "Dexec-move"  (fn [rest] (editor/run-command "dired-execute-move"        (string/trim rest))))
(colon/define "Dexec-delete" (fn [&]   (editor/run-command "dired-execute-deletion")))
