# Language keyword tables for syntax highlighting.

(define-syntax "janet"
  ["defn" "defn-" "def" "def-" "var" "let" "if" "when" "unless"
   "do" "each" "for" "while" "loop" "break"
   "fn" "case" "match" "try" "catch" "protect"
   "import" "require" "native" "declare"
   "and" "or" "not" "in" "not-in"
   "true" "false" "nil"
   "magma/trim" "magma/trim-trailing" "magma/deep-merge"
   "magma/time-now" "magma/debug-log"
   "string/slice" "string/split" "string/find"
   "string/replace" "string/replace-all" "string/repeat"
   "buffer/create" "buffer/insert" "buffer/delete" "buffer/slice"
   "buffer/current" "buffer/len" "buffer/line-count" "buffer/set-cursor"
   "buffer/cursor" "buffer/set-highlights" "buffer/clear-highlights"
   "editor/set-mode" "option/get" "option/set"
   "keymap/set" "command/define"
   "math/floor" "os/shell"
   "print" "table/new" "array/new" "spice"
   "eachp" "eachk" "accumulate" "generate"
   "coro" "resume" "yield" "run"
   "thread" "fiber" "net" "os"
   "peg" "parser" "marshal" "unmarshal"
   "env" "documentation" "quasiquote" "unquote"
   "splice" "short-fn" "defmacro"])

(define-syntax "javascript"
  ["function" "var" "let" "const" "if" "else" "for" "while"
   "do" "switch" "case" "break" "continue" "return"
   "class" "extends" "new" "this" "super"
   "import" "export" "from" "as" "default"
   "try" "catch" "finally" "throw"
   "async" "await" "yield" "typeof" "instanceof"
   "true" "false" "null" "undefined"
   "console" "Array" "Object" "String" "Number" "JSON"
   "Promise" "Map" "Set" "Symbol" "BigInt"])

(define-syntax "typescript"
  ["function" "var" "let" "const" "if" "else" "for" "while"
   "do" "switch" "case" "break" "continue" "return"
   "class" "extends" "implements" "new" "this" "super"
   "import" "export" "from" "as" "default"
   "try" "catch" "finally" "throw"
   "async" "await" "typeof" "instanceof"
   "interface" "type" "enum" "namespace" "module"
   "public" "private" "protected" "readonly" "static" "abstract"
   "true" "false" "null" "undefined"
   "string" "number" "boolean" "void" "any" "never" "unknown"])

(define-syntax "go"
  ["func" "var" "const" "type" "struct" "interface"
   "map" "chan" "go" "defer" "select"
   "if" "else" "for" "range" "switch" "case" "default"
   "break" "continue" "return" "fallthrough"
   "import" "package" "true" "false" "nil"
   "make" "len" "cap" "append" "copy" "delete" "close"
   "panic" "recover" "error"
   "int" "int8" "int16" "int32" "int64"
   "uint" "uint8" "uint16" "uint32" "uint64"
   "float32" "float64" "string" "bool" "byte" "rune"
   "error" "any"])

(define-syntax "c"
  ["int" "long" "short" "char" "float" "double" "void"
   "unsigned" "signed" "const" "volatile" "static" "extern"
   "auto" "register" "struct" "union" "enum" "typedef"
   "if" "else" "for" "while" "do" "switch" "case" "default"
   "break" "continue" "return" "goto" "sizeof"
   "include" "define" "ifdef" "ifndef" "endif" "pragma"
   "NULL" "true" "false" "size_t"])

(define-syntax "cpp"
  ["int" "long" "short" "char" "float" "double" "void" "bool"
   "unsigned" "signed" "const" "volatile" "static" "extern"
   "auto" "register" "struct" "union" "enum" "typedef"
   "class" "namespace" "template" "typename" "using"
   "public" "private" "protected" "virtual" "override" "final"
   "if" "else" "for" "while" "do" "switch" "case" "default"
   "break" "continue" "return" "goto" "sizeof"
   "new" "delete" "throw" "try" "catch"
   "include" "define" "ifdef" "ifndef" "endif" "pragma"
   "nullptr" "NULL" "true" "false"
   "string" "vector" "map" "set" "shared_ptr" "unique_ptr"
   "cout" "cin" "endl"
   "int8_t" "int16_t" "int32_t" "int64_t" "size_t"])

(define-syntax "ruby"
  ["def" "class" "module" "end" "if" "elsif" "else" "unless"
   "case" "when" "then" "for" "while" "until"
   "do" "begin" "rescue" "ensure" "raise" "throw"
   "return" "yield" "break" "next" "redo" "retry"
   "self" "nil" "true" "false"
   "puts" "print" "require" "include" "extend" "attr"
   "lambda" "proc" "new" "super" "defined?"])

(define-syntax "sh"
  ["if" "then" "else" "elif" "fi" "for" "while" "until"
   "do" "done" "case" "esac" "select"
   "function" "return" "exit" "break" "continue"
   "export" "local" "readonly" "unset"
   "declare" "typeset" "echo" "printf" "read" "set" "unset"
   "source" "." "exec" "eval" "trap" "shift"
   "true" "false" "test" "let"])

(define-syntax "lua"
  ["function" "end" "if" "then" "else" "elseif" "for"
   "while" "do" "repeat" "until" "return" "break"
   "local" "nil" "true" "false"
   "and" "or" "not" "in"
   "require" "print" "type" "pairs" "ipairs"
   "self" "yield" "error" "pcall" "xpcall"])

(define-syntax "java"
  ["class" "interface" "enum" "record" "extends" "implements"
   "public" "private" "protected" "static" "final" "abstract"
   "void" "int" "long" "short" "byte" "float" "double" "char" "boolean"
   "if" "else" "for" "while" "do" "switch" "case" "default"
   "break" "continue" "return" "new" "this" "super"
   "try" "catch" "finally" "throw" "throws"
   "import" "package" "null" "true" "false"
   "String" "System" "Integer" "Double" "Boolean" "Object"
   "synchronized" "volatile" "transient" "native" "strictfp"])

(define-syntax "kotlin"
  ["fun" "val" "var" "class" "data" "object" "companion"
   "interface" "enum" "sealed" "open" "abstract"
   "if" "else" "when" "for" "while" "do" "return"
   "try" "catch" "finally" "throw"
   "import" "package" "null" "true" "false"
   "override" "inner" "inline" "suspend" "tailrec"
   "this" "super" "is" "as" "in" "typeof"])

(define-syntax "swift"
  ["func" "var" "let" "class" "struct" "enum" "protocol"
   "extension" "import" "return" "if" "else" "for" "while"
   "switch" "case" "default" "break" "continue"
   "try" "catch" "throw" "throws" "rethrows"
   "guard" "defer" "inout" "mutating" "nonmutating"
   "public" "private" "internal" "fileprivate" "open"
   "true" "false" "nil" "self" "super"
   "in" "is" "as" "where" "associatedtype"
   "Int" "Double" "Float" "Bool" "String" "Array" "Dictionary" "Set"
   "print" "fatalError"])

(define-syntax "haskell"
  ["module" "where" "import" "qualified" "as" "hiding"
   "data" "type" "newtype" "class" "instance" "deriving"
   "let" "in" "if" "then" "else" "case" "of"
   "do" "where" "pure" "return"
   "True" "False" "Nothing" "Just" "Left" "Right"
   "map" "filter" "foldr" "foldl" "print" "putStrLn"])

(define-syntax "elixir"
  ["def" "defp" "defmodule" "defstruct" "defprotocol"
   "defimpl" "defmacro" "defmacrop" "defguard" "defguardp"
   "defexception" "defcallback" "defdelegate" "defoverridable"
   "if" "else" "unless" "cond" "case" "for" "with"
   "do" "end" "fn" "when" "true" "false" "nil"
   "raise" "throw" "try" "rescue" "catch" "after"
   "import" "alias" "use" "require" "receive"
   "send" "spawn" "self" "Map" "List" "String"])

(define-syntax "erlang"
  ["module" "export" "import" "define"
   "if" "case" "of" "when" "end" "receive" "after"
   "fun" "let" "true" "false"
   "record" "type" "spec" "callback" "define"
   "spawn" "send" "self" "link" "monitor"
   "list_to_binary" "binary_to_list" "tuple_to_list"])

(define-syntax "nim"
  ["proc" "func" "method" "iterator" "template" "macro"
   "type" "var" "let" "const" "result" "self"
   "if" "elif" "else" "case" "of" "for" "while"
   "try" "except" "finally" "raise" "return" "yield"
   "import" "from" "export" "include"
   "true" "false" "nil"
   "discard" "block" "break" "continue" "asm"
   "int" "int8" "int16" "int32" "int64"
   "uint" "float" "float32" "float64" "bool" "char" "string"
   "seq" "array" "tuple" "set" "ref" "ptr" "object" "enum"])

(define-syntax "zig"
  ["fn" "var" "const" "pub" "export" "extern" "inline"
   "struct" "enum" "union" "error" "packed"
   "if" "else" "for" "while" "switch" "continue" "break" "return"
   "defer" "errdefer" "catch" "try" "resume" "suspend"
   "comptime" "usingnamespace" "test"
   "true" "false" "null" "undefined"
   "u8" "u16" "u32" "u64" "usize"
   "i8" "i16" "i32" "i64" "isize"
   "f32" "f64" "bool" "void" "anyerror" "anytype"
   "print" "allocator" "Allocator"])

(define-syntax "nix"
  ["with" "let" "in" "if" "then" "else" "assert"
   "rec" "inherit" "import" "true" "false" "null"
   "builtins" "lib" "pkgs"
   "map" "filter" "foldl'" "concatMap" "hasAttr" "elem"])

(define-syntax "rust"
  ["fn" "let" "mut" "const" "static" "if" "else" "match"
   "for" "while" "loop" "in" "return" "break" "continue"
   "struct" "enum" "impl" "trait" "pub" "use" "mod" "crate"
   "self" "super" "ref" "move" "as" "type"
   "true" "false" "Some" "None" "Ok" "Err"
   "i8" "i16" "i32" "i64" "i128" "isize"
   "u8" "u16" "u32" "u64" "u128" "usize"
   "f32" "f64" "bool" "char" "str" "String" "Vec"
   "Box" "Rc" "Arc" "Option" "Result"
   "unsafe" "async" "await" "dyn" "where"
   "println" "format" "vec" "print"])

(print "syntax languages loaded")
