# ============================================================
# Magma — Vim keybindings (loaded after vim.janet)
# ============================================================

# ── Normal mode (vim layer) ──────────────────────────────
# Motions
(keymap/set "h" "cursor-left" :vim)
(keymap/set "j" "cursor-down" :vim)
(keymap/set "k" "cursor-up" :vim)
(keymap/set "l" "cursor-right" :vim)
(keymap/set "left" "cursor-left" :vim)
(keymap/set "right" "cursor-right" :vim)
(keymap/set "up" "cursor-up" :vim)
(keymap/set "down" "cursor-down" :vim)
(keymap/set "home" "line-start" :vim)
(keymap/set "end" "line-end" :vim)
(keymap/set "w" "move-word-forward" :vim)
(keymap/set "b" "move-word-back" :vim)
(keymap/set "e" "move-word-end" :vim)
(keymap/set "$" "line-end" :vim)
(keymap/set "^" "move-to-first-char" :vim)
(keymap/set "}" "move-paragraph-forward" :vim)
(keymap/set "{" "move-paragraph-back" :vim)
(keymap/set ")" "move-sentence-forward" :vim)
(keymap/set "(" "move-sentence-back" :vim)
(keymap/set "G" "goto-buffer-end" :vim)
(keymap/set "%" "goto-matching-brace" :vim)

# Mode transitions
(keymap/set "i" "vim-enter-insert" :vim)
(keymap/set "a" "append" :vim)
(keymap/set "A" "append-eol" :vim)
(keymap/set "o" "open-line-below" :vim)
(keymap/set "O" "open-line-above" :vim)
(keymap/set "I" "insert-bol" :vim)
(keymap/set "v" "vim-enter-visual" :vim)
(keymap/set "V" "enter-visual-line-mode" :vim)
(keymap/set "ctrl-v" "enter-visual-block-mode" :vim)
(keymap/set "R" "vim-enter-replace" :vim)
(keymap/set ":" "vim-enter-command" :vim)
(keymap/set "/" "enter-search-forward" :vim)
(keymap/set "?" "enter-search-backward" :vim)

# Search
(keymap/set "n" "repeat-search" :vim)
(keymap/set "N" "reverse-search" :vim)
(keymap/set "*" "find-word-under-cursor" :vim)
(keymap/set "#" "find-word-under-cursor-back" :vim)
(keymap/set ";" "repeat-last-find" :vim)
(keymap/set "," "reverse-last-find" :vim)

# Editing
(keymap/set "x" "delete-char" :vim)
(keymap/set "X" "backspace" :vim)
(keymap/set "u" "undo" :vim)
(keymap/set "ctrl-r" "redo" :vim)
(keymap/set "J" "join-lines" :vim)
(keymap/set "D" "delete-to-eol" :vim)
(keymap/set "C" "change-to-eol" :vim)
(keymap/set "Y" "yank-to-eol" :vim)

# Put
(keymap/set "p" "put" :vim)
(keymap/set "P" "put-before" :vim)
(keymap/set "~" "toggle-case" :vim)
(keymap/set "." "repeat-last-change" :vim)

# Line operations
(keymap/set ">" "indent-line" :vim)
(keymap/set "<" "deindent-line" :vim)
(keymap/set "=" "autoindent-line" :vim)

# Scroll
(keymap/set "ctrl-u" "scroll-half-page-up" :vim)
(keymap/set "ctrl-d" "scroll-half-page-down" :vim)
(keymap/set "ctrl-f" "scroll-page-down" :vim)
(keymap/set "ctrl-b" "scroll-page-up" :vim)
(keymap/set "ctrl-e" "scroll-line-down" :vim)
(keymap/set "ctrl-y" "scroll-line-up" :vim)
(keymap/set "H" "goto-screen-top" :vim)
(keymap/set "M" "goto-screen-middle" :vim)
(keymap/set "L" "goto-screen-bottom" :vim)

# Misc
(keymap/set "ctrl-a" "increment-number" :vim)
(keymap/set "ctrl-x" "decrement-number" :vim)
(keymap/set "ctrl-^" "alternate-buffer" :vim)
(keymap/set "ctrl-d" "multi-cursor-next-occurrence" :vim)
(keymap/set "esc" "multi-cursor-clear" :vim)

# Two-key prefixes
(keymap/set "gg" "goto-buffer-start" :vim)
(keymap/set "gi" "go-to-last-insert-pos" :vim)
(keymap/set "g~" "toggle-case" :vim)
(keymap/set "gu" "lowercase-region" :vim)
(keymap/set "gU" "uppercase-region" :vim)
(keymap/set "gp" "put-after-cursor" :vim)
(keymap/set "gP" "put-before-cursor" :vim)
(keymap/set "gv" "reselect-last-visual" :vim)
(keymap/set "gt" "buffer-next" :vim)
(keymap/set "gT" "buffer-prev" :vim)
(keymap/set "g;" "goto-older-change" :vim)
(keymap/set "g," "goto-newer-change" :vim)
(keymap/set "zt" "scroll-to-top" :vim)
(keymap/set "zz" "scroll-to-middle" :vim)
(keymap/set "zb" "scroll-to-bottom" :vim)
(keymap/set "ZQ" "force-quit" :vim)
(keymap/set "ZZ" "save-and-quit" :vim)
(keymap/set "ctrl-ws" "window-split" :vim)
(keymap/set "ctrl-wv" "window-vsplit" :vim)
(keymap/set "ctrl-wq" "window-close" :vim)
(keymap/set "ctrl-wc" "window-close" :vim)
(keymap/set "ctrl-wh" "window-focus-left" :vim)
(keymap/set "ctrl-wj" "window-focus-down" :vim)
(keymap/set "ctrl-wk" "window-focus-up" :vim)
(keymap/set "ctrl-wl" "window-focus-right" :vim)
(keymap/set "ctrl-ww" "window-next" :vim)
(keymap/set "ctrl-wctrl-w" "window-next" :vim)
(keymap/set "[I" "keyword-context" :vim)
(keymap/set "]I" "find-word-under-cursor" :vim)

# ── Insert mode ──────────────────────────────────────────
(keymap/set "esc" "vim-exit-insert" :insert)
(keymap/set "ctrl-c" "vim-exit-insert" :insert)
(keymap/set "ctrl-[" "vim-exit-insert" :insert)
(keymap/set "ctrl-n" "completion-next" :insert)
(keymap/set "ctrl-p" "completion-prev" :insert)
(keymap/set "tab" "snippet-next-tabstop" :insert)
(keymap/set "ctrl-]" "snippet-expand" :insert)
(keymap/set "backspace" "backspace" :insert)
(keymap/set "delete" "delete-char" :insert)
(keymap/set "return" "newline" :insert)
(keymap/set "left" "cursor-left" :insert)
(keymap/set "right" "cursor-right" :insert)
(keymap/set "up" "cursor-up" :insert)
(keymap/set "down" "cursor-down" :insert)
(keymap/set "home" "line-start" :insert)
(keymap/set "end" "line-end" :insert)
(keymap/set "ctrl-w" "delete-word-back" :insert)
(keymap/set "ctrl-u" "delete-to-bol" :insert)

# ── Visual mode ──────────────────────────────────────────
(keymap/set "esc" "vim-exit-visual" :visual)
(keymap/set "ctrl-c" "vim-exit-visual" :visual)
(keymap/set "h" "cursor-left" :visual)
(keymap/set "j" "cursor-down" :visual)
(keymap/set "k" "cursor-up" :visual)
(keymap/set "l" "cursor-right" :visual)
(keymap/set "left" "cursor-left" :visual)
(keymap/set "right" "cursor-right" :visual)
(keymap/set "up" "cursor-up" :visual)
(keymap/set "down" "cursor-down" :visual)
(keymap/set "0" "line-start" :visual)
(keymap/set "$" "line-end" :visual)
(keymap/set "home" "line-start" :visual)
(keymap/set "end" "line-end" :visual)
(keymap/set "d" "vim-visual-delete" :visual)
(keymap/set "x" "vim-visual-delete" :visual)
(keymap/set "c" "vim-visual-change" :visual)
(keymap/set "y" "vim-visual-yank" :visual)
(keymap/set "~" "toggle-case-visual" :visual)
(keymap/set "u" "lowercase-visual" :visual)
(keymap/set "U" "uppercase-visual" :visual)
(keymap/set "I" "block-insert" :visual)
(keymap/set "A" "block-append" :visual)

# ── Replace mode ─────────────────────────────────────────
(keymap/set "esc" "vim-exit-replace" :replace)
(keymap/set "ctrl-c" "vim-exit-replace" :replace)
(keymap/set "left" "cursor-left" :replace)
(keymap/set "right" "cursor-right" :replace)
(keymap/set "up" "cursor-up" :replace)
(keymap/set "down" "cursor-down" :replace)

# ── Search mode ──────────────────────────────────────────
(keymap/set "esc" "vim-exit-search" :search)
(keymap/set "ctrl-c" "vim-exit-search" :search)
(keymap/set "return" "search-execute" :search)
(keymap/set "backspace" "search-backspace" :search)

# ── Command mode ─────────────────────────────────────────
(keymap/set "return" "command-execute" :command)
(keymap/set "esc" "vim-exit-command" :command)
(keymap/set "ctrl-c" "vim-exit-command" :command)
(keymap/set "backspace" "command-backspace" :command)
(keymap/set "tab" "command-complete" :command)
(keymap/set "ctrl-n" "command-complete" :command)
(keymap/set "ctrl-p" "command-complete-prev" :command)
(keymap/set "down" "command-complete" :command)
(keymap/set "up" "command-complete-prev" :command)

# ── Global (all modes) ──────────────────────────────────
(keymap/set "ctrl-s" "save-buffer")
(keymap/set "ctrl-q" "quit")
(keymap/set "ctrl-z" "undo")
(keymap/set "ctrl-y" "redo")
(keymap/set "ctrl-p" "find-files")
(keymap/set "gf" "open-file-at-cursor")
(keymap/set "g f" "open-file-at-cursor")
(keymap/set "return" "open-file-at-cursor")
(keymap/set "gt" "tabnext")
(keymap/set "g t" "tabnext")
(keymap/set "gT" "tabprev")
(keymap/set "g T" "tabprev")
